import About from "@/components/About";
import Details from "@/components/Details";
import Events from "@/components/Events";
import Facilities from "@/components/Facilities";
import Hero from "@/components/Hero";
import Learn from "@/components/Learn";
import Media from "@/components/Media";
import Review from "@/components/Review";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Riyadh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="main_conatiner">
        <Hero />
        <About /> 
        <Facilities />
        <Details />
        <Learn />
        <Events />
        <Media />
        <Review />
      </main>
    </>
  );
}
