import About from "@/components/About";
import Events from "@/components/Events";
import Hero from "@/components/Hero";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Riyadh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="main_conatiner">
        <Hero />
        <About />
        <Events />
      </main>
    </>
  );
}
